/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Component;
import javax.swing.JPanel;

/**
 *
 * @author Gabriel
 */
public class Inicio extends javax.swing.JFrame {

    public Inicio() {
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        initComponents();
        setLocationRelativeTo(null);
        setExtendedState(Inicio.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelFundoInicio = new javax.swing.JPanel();
        barMenu = new javax.swing.JMenuBar();
        mInserir = new javax.swing.JMenu();
        imImagem = new javax.swing.JMenuItem();
        mListar = new javax.swing.JMenu();
        imImagens = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout painelFundoInicioLayout = new javax.swing.GroupLayout(painelFundoInicio);
        painelFundoInicio.setLayout(painelFundoInicioLayout);
        painelFundoInicioLayout.setHorizontalGroup(
            painelFundoInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        painelFundoInicioLayout.setVerticalGroup(
            painelFundoInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        getContentPane().add(painelFundoInicio, java.awt.BorderLayout.CENTER);

        mInserir.setText("Inserir");

        imImagem.setText("Imagem");
        imImagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imImagemActionPerformed(evt);
            }
        });
        mInserir.add(imImagem);

        barMenu.add(mInserir);

        mListar.setText("Listar");

        imImagens.setText("Imagens");
        imImagens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imImagensActionPerformed(evt);
            }
        });
        mListar.add(imImagens);

        barMenu.add(mListar);

        setJMenuBar(barMenu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void imImagensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imImagensActionPerformed
        ListarImagemGUI gui = new ListarImagemGUI();
        painelFundoInicio.setVisible(false);
        add(gui.getPainelFundoLista(), 0);
    }//GEN-LAST:event_imImagensActionPerformed

    private void imImagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imImagemActionPerformed
        //InserirImagemGUI gui = new InserirImagemGUI();
        painelFundoInicio.setVisible(false);
        // add(gui.getPainelFundoInserir(), 0);
    }//GEN-LAST:event_imImagemActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barMenu;
    private javax.swing.JMenuItem imImagem;
    private javax.swing.JMenuItem imImagens;
    private javax.swing.JMenu mInserir;
    private javax.swing.JMenu mListar;
    private javax.swing.JPanel painelFundoInicio;
    // End of variables declaration//GEN-END:variables
}
